app.notification.to.tenant.book.accept=Dear customer, your booking has been accepted by the owner. Enjoy your new living space.
app.notification.to.tenant.book.accept.title=Booking Request Accepted

app.notification.to.tenant.book.reject=Dear customer, your booking has been rejected by the owner. Please explore other available spaces.
app.notification.to.tenant.book.reject.title=Booking Request Rejected

app.notification.to.owner.property.approved=Dear owner, your property has been reviewed and approved by the admin. Thank you for trusting our platform.
app.notification.to.owner.property.approved.title=Property Approved

app.notification.to.owner.property.rejected=Dear owner, your property has been reviewed and rejected by the admin. Thank you for using our platform.
app.notification.to.owner.property.rejected.title=Property Rejected

app.notification.to.admin.new.property.uploaded=A new property has been posted to the listing. Please review and take appropriate action.
app.notification.to.admin.new.property.title=New Property Uploaded

app.notification.to.admin.add.new.customer=Dear admin, a new customer has been added to the system. Please check the owner or tenant page for details.
app.notification.to.admin.add.new.customer.title=New Customer Registered

app.notification.to.owner.payment.warning=Dear owner, your property has been approved but is not yet publicly listed at user site. To make it visible as public, please complete the payment through eSewa from your property details page.
app.notification.to.owner.payment.warning.title=Payment Required for Listing

app.notification.to.owner.payment.success=Your payment was successful and has been received by the admin.And now your property listed as publicly.
app.notification.to.owner.payment.success.title=Payment Successful

app.notification.to.owner.payment.failed=Your payment failed due to an issue. Please try again from the payment page.
app.notification.to.owner.payment.failed.title=Payment Failed

app.notification.to.admin.payment.success=Dear admin, a property listing payment has been received from an owner. Please verify it via eSewa and check the payment page.
app.notification.to.admin.payment.success.title=Payment Received Successfully

app.notification.to.tenant.warning=Dear customer, your booking request has been submitted successfully. Please visit the property location within 3 days using the provided navigation; otherwise, your booking request may be canceled.
app.notification.to.tenant.warning.title=Visit Property Location

app.notification.to.owner.property.booked=Dear owner someone send a booking request to reserve your property, please check the reservation details.
app.notification.to.owner.property.booked.title=Request to book property.